/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyInvestRouteImport } from './routes/why-invest'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalPropertiesRouteImport } from './routes/portal/properties'
import { Route as PortalProjectsRouteImport } from './routes/portal/projects'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalLeadsRouteImport } from './routes/portal/leads'
import { Route as PortalContentRouteImport } from './routes/portal/content'
import { Route as PortalBlogsRouteImport } from './routes/portal/blogs'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as PortalBlogsIndexRouteImport } from './routes/portal/blogs/index'
import { Route as PortalBlogsIdRouteImport } from './routes/portal/blogs.$id'

const WhyInvestRoute = WhyInvestRouteImport.update({
  id: '/why-invest',
  path: '/why-invest',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPropertiesRoute = PortalPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsRoute = PortalProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLeadsRoute = PortalLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContentRoute = PortalContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBlogsRoute = PortalBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => PortalRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const PortalBlogsIndexRoute = PortalBlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalBlogsRoute,
} as any)
const PortalBlogsIdRoute = PortalBlogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-invest': typeof WhyInvestRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/portal/blogs': typeof PortalBlogsRouteWithChildren
  '/portal/content': typeof PortalContentRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/properties': typeof PortalPropertiesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/blogs/$id': typeof PortalBlogsIdRoute
  '/portal/blogs/': typeof PortalBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-invest': typeof WhyInvestRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/properties': typeof PortalPropertiesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/portal': typeof PortalIndexRoute
  '/portal/blogs/$id': typeof PortalBlogsIdRoute
  '/portal/blogs': typeof PortalBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-invest': typeof WhyInvestRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/portal/blogs': typeof PortalBlogsRouteWithChildren
  '/portal/content': typeof PortalContentRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/properties': typeof PortalPropertiesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/blogs/$id': typeof PortalBlogsIdRoute
  '/portal/blogs/': typeof PortalBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/guides'
    | '/portal'
    | '/properties'
    | '/sitemap.xml'
    | '/why-invest'
    | '/guides/$slug'
    | '/portal/blogs'
    | '/portal/content'
    | '/portal/leads'
    | '/portal/login'
    | '/portal/projects'
    | '/portal/properties'
    | '/portal/settings'
    | '/projects/$slug'
    | '/portal/'
    | '/portal/blogs/$id'
    | '/portal/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/guides'
    | '/properties'
    | '/sitemap.xml'
    | '/why-invest'
    | '/guides/$slug'
    | '/portal/content'
    | '/portal/leads'
    | '/portal/login'
    | '/portal/projects'
    | '/portal/properties'
    | '/portal/settings'
    | '/projects/$slug'
    | '/portal'
    | '/portal/blogs/$id'
    | '/portal/blogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/guides'
    | '/portal'
    | '/properties'
    | '/sitemap.xml'
    | '/why-invest'
    | '/guides/$slug'
    | '/portal/blogs'
    | '/portal/content'
    | '/portal/leads'
    | '/portal/login'
    | '/portal/projects'
    | '/portal/properties'
    | '/portal/settings'
    | '/projects/$slug'
    | '/portal/'
    | '/portal/blogs/$id'
    | '/portal/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PropertiesRoute: typeof PropertiesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhyInvestRoute: typeof WhyInvestRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-invest': {
      id: '/why-invest'
      path: '/why-invest'
      fullPath: '/why-invest'
      preLoaderRoute: typeof WhyInvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/properties': {
      id: '/portal/properties'
      path: '/properties'
      fullPath: '/portal/properties'
      preLoaderRoute: typeof PortalPropertiesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects': {
      id: '/portal/projects'
      path: '/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalProjectsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/leads': {
      id: '/portal/leads'
      path: '/leads'
      fullPath: '/portal/leads'
      preLoaderRoute: typeof PortalLeadsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/content': {
      id: '/portal/content'
      path: '/content'
      fullPath: '/portal/content'
      preLoaderRoute: typeof PortalContentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/blogs': {
      id: '/portal/blogs'
      path: '/blogs'
      fullPath: '/portal/blogs'
      preLoaderRoute: typeof PortalBlogsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/portal/blogs/': {
      id: '/portal/blogs/'
      path: '/'
      fullPath: '/portal/blogs/'
      preLoaderRoute: typeof PortalBlogsIndexRouteImport
      parentRoute: typeof PortalBlogsRoute
    }
    '/portal/blogs/$id': {
      id: '/portal/blogs/$id'
      path: '/$id'
      fullPath: '/portal/blogs/$id'
      preLoaderRoute: typeof PortalBlogsIdRouteImport
      parentRoute: typeof PortalBlogsRoute
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface PortalBlogsRouteChildren {
  PortalBlogsIdRoute: typeof PortalBlogsIdRoute
  PortalBlogsIndexRoute: typeof PortalBlogsIndexRoute
}

const PortalBlogsRouteChildren: PortalBlogsRouteChildren = {
  PortalBlogsIdRoute: PortalBlogsIdRoute,
  PortalBlogsIndexRoute: PortalBlogsIndexRoute,
}

const PortalBlogsRouteWithChildren = PortalBlogsRoute._addFileChildren(
  PortalBlogsRouteChildren,
)

interface PortalRouteChildren {
  PortalBlogsRoute: typeof PortalBlogsRouteWithChildren
  PortalContentRoute: typeof PortalContentRoute
  PortalLeadsRoute: typeof PortalLeadsRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalProjectsRoute: typeof PortalProjectsRoute
  PortalPropertiesRoute: typeof PortalPropertiesRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBlogsRoute: PortalBlogsRouteWithChildren,
  PortalContentRoute: PortalContentRoute,
  PortalLeadsRoute: PortalLeadsRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalProjectsRoute: PortalProjectsRoute,
  PortalPropertiesRoute: PortalPropertiesRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GuidesRoute: GuidesRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PropertiesRoute: PropertiesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhyInvestRoute: WhyInvestRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
