/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyInvestRouteImport } from './routes/why-invest'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SonoraGardenResidencesRouteImport } from './routes/sonora-garden-residences'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as PortalSettingsRouteImport } from './routes/portal/settings'
import { Route as PortalPropertiesRouteImport } from './routes/portal/properties'
import { Route as PortalProjectsRouteImport } from './routes/portal/projects'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalLeadsRouteImport } from './routes/portal/leads'
import { Route as PortalFaqsRouteImport } from './routes/portal/faqs'
import { Route as PortalContentRouteImport } from './routes/portal/content'
import { Route as PortalBlogsRouteImport } from './routes/portal/blogs'
import { Route as PortalApplicationsRouteImport } from './routes/portal/applications'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as PortalBlogsIndexRouteImport } from './routes/portal/blogs/index'
import { Route as PortalBlogsIdRouteImport } from './routes/portal/blogs.$id'

const WhyInvestRoute = WhyInvestRouteImport.update({
  id: '/why-invest',
  path: '/why-invest',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SonoraGardenResidencesRoute = SonoraGardenResidencesRouteImport.update({
  id: '/sonora-garden-residences',
  path: '/sonora-garden-residences',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPropertiesRoute = PortalPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsRoute = PortalProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLeadsRoute = PortalLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFaqsRoute = PortalFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContentRoute = PortalContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBlogsRoute = PortalBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApplicationsRoute = PortalApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => PortalRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBlogsIndexRoute = PortalBlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalBlogsRoute,
} as any)
const PortalBlogsIdRoute = PortalBlogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sonora-garden-residences': typeof SonoraGardenResidencesRoute
  '/terms': typeof TermsRoute
  '/why-invest': typeof WhyInvestRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/portal/applications': typeof PortalApplicationsRoute
  '/portal/blogs': typeof PortalBlogsRouteWithChildren
  '/portal/content': typeof PortalContentRoute
  '/portal/faqs': typeof PortalFaqsRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/properties': typeof PortalPropertiesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/blogs/$id': typeof PortalBlogsIdRoute
  '/portal/blogs/': typeof PortalBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sonora-garden-residences': typeof SonoraGardenResidencesRoute
  '/terms': typeof TermsRoute
  '/why-invest': typeof WhyInvestRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/portal/applications': typeof PortalApplicationsRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/faqs': typeof PortalFaqsRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/properties': typeof PortalPropertiesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/blogs/$id': typeof PortalBlogsIdRoute
  '/portal/blogs': typeof PortalBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sonora-garden-residences': typeof SonoraGardenResidencesRoute
  '/terms': typeof TermsRoute
  '/why-invest': typeof WhyInvestRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/portal/applications': typeof PortalApplicationsRoute
  '/portal/blogs': typeof PortalBlogsRouteWithChildren
  '/portal/content': typeof PortalContentRoute
  '/portal/faqs': typeof PortalFaqsRoute
  '/portal/leads': typeof PortalLeadsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/properties': typeof PortalPropertiesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/blogs/$id': typeof PortalBlogsIdRoute
  '/portal/blogs/': typeof PortalBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/portal'
    | '/privacy'
    | '/properties'
    | '/sitemap.xml'
    | '/sonora-garden-residences'
    | '/terms'
    | '/why-invest'
    | '/guides/$slug'
    | '/portal/applications'
    | '/portal/blogs'
    | '/portal/content'
    | '/portal/faqs'
    | '/portal/leads'
    | '/portal/login'
    | '/portal/projects'
    | '/portal/properties'
    | '/portal/settings'
    | '/projects/$slug'
    | '/guides/'
    | '/portal/'
    | '/portal/blogs/$id'
    | '/portal/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/properties'
    | '/sitemap.xml'
    | '/sonora-garden-residences'
    | '/terms'
    | '/why-invest'
    | '/guides/$slug'
    | '/portal/applications'
    | '/portal/content'
    | '/portal/faqs'
    | '/portal/leads'
    | '/portal/login'
    | '/portal/projects'
    | '/portal/properties'
    | '/portal/settings'
    | '/projects/$slug'
    | '/guides'
    | '/portal'
    | '/portal/blogs/$id'
    | '/portal/blogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/portal'
    | '/privacy'
    | '/properties'
    | '/sitemap.xml'
    | '/sonora-garden-residences'
    | '/terms'
    | '/why-invest'
    | '/guides/$slug'
    | '/portal/applications'
    | '/portal/blogs'
    | '/portal/content'
    | '/portal/faqs'
    | '/portal/leads'
    | '/portal/login'
    | '/portal/projects'
    | '/portal/properties'
    | '/portal/settings'
    | '/projects/$slug'
    | '/guides/'
    | '/portal/'
    | '/portal/blogs/$id'
    | '/portal/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  PropertiesRoute: typeof PropertiesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SonoraGardenResidencesRoute: typeof SonoraGardenResidencesRoute
  TermsRoute: typeof TermsRoute
  WhyInvestRoute: typeof WhyInvestRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-invest': {
      id: '/why-invest'
      path: '/why-invest'
      fullPath: '/why-invest'
      preLoaderRoute: typeof WhyInvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sonora-garden-residences': {
      id: '/sonora-garden-residences'
      path: '/sonora-garden-residences'
      fullPath: '/sonora-garden-residences'
      preLoaderRoute: typeof SonoraGardenResidencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/properties': {
      id: '/portal/properties'
      path: '/properties'
      fullPath: '/portal/properties'
      preLoaderRoute: typeof PortalPropertiesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects': {
      id: '/portal/projects'
      path: '/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalProjectsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/leads': {
      id: '/portal/leads'
      path: '/leads'
      fullPath: '/portal/leads'
      preLoaderRoute: typeof PortalLeadsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/faqs': {
      id: '/portal/faqs'
      path: '/faqs'
      fullPath: '/portal/faqs'
      preLoaderRoute: typeof PortalFaqsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/content': {
      id: '/portal/content'
      path: '/content'
      fullPath: '/portal/content'
      preLoaderRoute: typeof PortalContentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/blogs': {
      id: '/portal/blogs'
      path: '/blogs'
      fullPath: '/portal/blogs'
      preLoaderRoute: typeof PortalBlogsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/applications': {
      id: '/portal/applications'
      path: '/applications'
      fullPath: '/portal/applications'
      preLoaderRoute: typeof PortalApplicationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/blogs/': {
      id: '/portal/blogs/'
      path: '/'
      fullPath: '/portal/blogs/'
      preLoaderRoute: typeof PortalBlogsIndexRouteImport
      parentRoute: typeof PortalBlogsRoute
    }
    '/portal/blogs/$id': {
      id: '/portal/blogs/$id'
      path: '/$id'
      fullPath: '/portal/blogs/$id'
      preLoaderRoute: typeof PortalBlogsIdRouteImport
      parentRoute: typeof PortalBlogsRoute
    }
  }
}

interface PortalBlogsRouteChildren {
  PortalBlogsIdRoute: typeof PortalBlogsIdRoute
  PortalBlogsIndexRoute: typeof PortalBlogsIndexRoute
}

const PortalBlogsRouteChildren: PortalBlogsRouteChildren = {
  PortalBlogsIdRoute: PortalBlogsIdRoute,
  PortalBlogsIndexRoute: PortalBlogsIndexRoute,
}

const PortalBlogsRouteWithChildren = PortalBlogsRoute._addFileChildren(
  PortalBlogsRouteChildren,
)

interface PortalRouteChildren {
  PortalApplicationsRoute: typeof PortalApplicationsRoute
  PortalBlogsRoute: typeof PortalBlogsRouteWithChildren
  PortalContentRoute: typeof PortalContentRoute
  PortalFaqsRoute: typeof PortalFaqsRoute
  PortalLeadsRoute: typeof PortalLeadsRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalProjectsRoute: typeof PortalProjectsRoute
  PortalPropertiesRoute: typeof PortalPropertiesRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalApplicationsRoute: PortalApplicationsRoute,
  PortalBlogsRoute: PortalBlogsRouteWithChildren,
  PortalContentRoute: PortalContentRoute,
  PortalFaqsRoute: PortalFaqsRoute,
  PortalLeadsRoute: PortalLeadsRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalProjectsRoute: PortalProjectsRoute,
  PortalPropertiesRoute: PortalPropertiesRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  PropertiesRoute: PropertiesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SonoraGardenResidencesRoute: SonoraGardenResidencesRoute,
  TermsRoute: TermsRoute,
  WhyInvestRoute: WhyInvestRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
